### PR TITLE
Don't break when console.log() encounters a circular JSON structure

### PR DESCRIPTION
**Pull request by pasieronen**
- [X] This is a **bugfix**
- [ ] This is a new **feature**
- [ ] This is a **code refactor**
- [ ] This is a **test update**
- [ ] This is a **typo fix**
- [ ] This is a **metadata update**

### For Bugs and Features; did you add new tests?

Yes.

### Motivation / Use-Case

Currently `console.log(circular)` and `console.log("%j", circular)` work (produce output `[Circular]`), but `console.log("foo", circular)` throws an exception.

### Breaking Changes

Not breaking change.

### CODE REVIEW

**Comment by shellscape** [comment]
I'm interested in the greater use-case, or rather a common case in which this is an issue. On the surface it looks mighty edge-casey, but please do elaborate.

**Comment by pasieronen** [comment]
I'm trying to migrate an existing app from mocha-phantomjs to mocha-chrome. Our tests work fine in mocha-phantomjs and plain Chrome browser, but fail in mocha-chrome, because in some places our code calls `console.log` with its internal data structure, which happens to be circular...

**Comment by shellscape** [comment]
Well, you removed the node and other version sections in the issue template (you should never, ever remove sections of an issue template - it's there for a reason), so I can't tell what version of Node you're working with, but on Node v9+ this works as expected natively:

```console
→ node
> a = { name: 'Groucho' };
{ name: 'Groucho' }
> b = { name: 'Harpo', sibling: a };
{ name: 'Harpo', sibling: { name: 'Groucho' } }
> a.sibling = b;
{ name: 'Harpo',
  sibling: { name: 'Groucho', sibling: [Circular] } }
> a
{ name: 'Groucho',
  sibling: { name: 'Harpo', sibling: [Circular] } }
> console.log(a)
{ name: 'Groucho',
  sibling: { name: 'Harpo', sibling: [Circular] } }
undefined
> console.log('foo', a)
foo { name: 'Groucho',
  sibling: { name: 'Harpo', sibling: [Circular] } }
undefined
```

**Comment by pasieronen** [comment]
Ah, the pull request template (https://github.com/shellscape/mocha-chrome/blob/master/.github/PULL_REQUEST_TEMPLATE.md) doesn't actually ask about Node version, only the issue request template does...

But I'm running Node v8.9.3 / NPM v5.5.1 on OSX, with mocha-chrome 1.0.3 and mocha 4.1.0.

The test "circular.html" I added shows what is broken: If a test case (or the code being tested in the browser) calls `console.log('foo', a)` (with a circular `a`),  it doesn't work, because it's not calling Node's or Chrome's `console.log` (both of which would work), but it's actually calling console.log here https://github.com/shellscape/mocha-chrome/blob/master/client/shim.js#L125, which calls console.format here https://github.com/shellscape/mocha-chrome/blob/master/client/shim.js#L78 (which currently handles circular structures in some cases, but not this particular one).

**Comment by shellscape** [comment]
Ah, that's my fault! I'll get that included in the PR template as soon as I get the chance. Thanks for the additional explanation. I've got a big life event this week so it'll probably be next week before I can get this released.

**Comment by pasieronen** [comment]
@shellscape Have you had a chance to do a release yet? (btw, big thanks for your work on mocha-chrome - just couple of weeks ago we finally switched our tests from mocha-phantomjs to mocha-chrome, and that made e.g. upgrading to React 16 really easy :)

**Comment by shellscape** [comment]
I'll take care of that right now.

**Pull request merged**
