### PR TITLE
add "debug" to unsupported console API

### PR DESCRIPTION
**Pull request by pgn-vole**
add "debug" to unsupported console API

### CODE REVIEW

**Comment by shellscape** [comment]
> Thank you for submitting a pull request! Please note that this template is not
optional. Please fill out **_all_** fields, or your pull request may be rejected.
Please do not delete this template. Please do remove this header to acknowledge this message.

Pull request templates are there for a reason.

**Comment by pgn-vole** [comment]
You are welcome @shellscape. I will not spend anymore time in contributing to this library.

**Comment by shellscape** [comment]
@pgn-vole I was quoting the pull request template. your pull request was rejected because you removed he pull request template and didn't properly explain your change. pull request templates usually aren't optional, and you'll find that true across most repos on Github these days - an important note if you plan to contribute to other repos in the future. 

>  I will not spend anymore time in contributing to this library

That's just poor form, but no skin off my back. Cheers, and best of luck to you!

**Comment by pgn-vole** [comment]
There are many other differents way to handle PR not following the conventions that simply closing it then with a one-liner. There is work behind it and I'm pretty sure we would both gain of it.

**Comment by shellscape** [comment]
@pgn-vole but that wasn't a one-line response; I quoted the important part of the pull request template as well. I'm sorry, but you chose either not to read it, or not to follow it (even after I quoted it for you!), and the PR template outlines exactly what the consequence for that is. You could have chosen to reply differently, or to edit your PR to conform to the template. Unfortunately, you did not make either of those choices. That may be due to a lack of experience with the platform, or a lack of experience with open source projects on the whole. But given that the warning and instruction is literally within the first two lines of the template, there's very little excuse here. Unfortunately the fault lies with you. You've already expressed your desire not to interact with the project further, which is totally fine and I harbor no ill will towards you for that sentiment, but I would highly advise taking this as a lesson in contribution to projects in the future, regardless of the project.

**Comment by pgn-vole** [comment]
>  Unfortunately, you did not make either of those choices.

Because you closed the PR. There is a review process workflow in Github. You would have had to simply request changes and I would have made them.

**Comment by shellscape** [comment]
Yeah, but again:

> Please fill out all fields, or your pull request may be rejected. Please do not delete this template.

The workflow doesn't exist if you don't start it properly. That's like saying there should be a discussion with someone submitting whitespace as a change with a removed template. Sorry, but this one is on you. Your PR was rejected because you chose not to follow the instructions. You can try and argue this until the cows come home, but the reason is in black and white, for all to see the moment that Pull Request button is clicked.

**Pull request closed without merging**
