### PR TITLE
Node 6 compatibility

### LINKED ISSUE #8: Add support of Node 6.x
Would it be possible to add support of Node 6.x ?
It is the current LTS and people in large companies (like myself) might be stuck on it. That would be a shame to not let them use this nice libary :)

### LINKED ISSUE #10: mocha-chrome: unexpected token
> Please note that this template is not optional. If you proceed with this form,
please fill out **_all_** fields, or your issue may be closed as "invalid."
Please do not delete this template. Please do remove this header to acknowledge this message.

* Operating System: macOS Sierra 10.12.6
* Node Version: v6.11.3
* NPM Version: 3.10.10
* mocha Version: 3.5.3
* mocha-chrome Version: 0.2.1
* chrome Version: 61.0.3163.100

- [ ] This is a **feature** request
- [x ] This is a **bug**

### Code

```js
  // code
```

### Expected Behavior
mocha-chrome should run tests in html file
### Actual Behavior
/Users/robhicks/.nvm/versions/node/v6.11.3/lib/node_modules/mocha-chrome/bin/mocha-chrome:89
(async function run () {
       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
### For Bugs; How can we reproduce the behavior?
Run the mocha-chrome command in an environment like mine.

### PR DESCRIPTION
**Pull request by pgn-vole**
Replaced async and await by promises to make the utility compatible with node 6.
Although it makes the code a bit less lean it makes the library usable by a much wider range of users.

Fixes #10 
Fixes #8

### CODE REVIEW

**Comment by shellscape** [comment]
@pgn-vole really appreciate that you took the time to put this together, but this isn't something I'm interested in merging or maintaining. mocha-chrome is going to remain Node 8+. 🍻

**Comment by shellscape** [comment]
@pgn-vole under MIT you're totally allowed to do that. I'd just ask that you add the proper attribution 😄

**Comment by grancalavera** [comment]
@shellscape is a shame you can't merge this pull request, we would prefer to contribute to your main project rather than forking away from it. This tool would allows us to move away from older parts of our toolchain.

As @pgn-vole mentioned, we are constrained to use an LTS version of node, and I would imagine some other organizations with similar constraints would benefit from using your project.

So kindly, we're asking one more time if you'd consider merging this PR, which if you thing about it, does not affect the features of your project.

**Comment by shellscape** [comment]
@grancalavera thanks for weighing and adding your thoughts. unfortunately I must decline that change, even in light of your impassioned plea. I have no interest in supporting older versions of Node outright, which don't support the async/await syntax natively. If you choose to fork and maintain a separate module, or an extension or slight modification of this module, then sincerely I wish you the absolute best! That's one of the great benefits to open source - the ability to pivot without restraint!

If you'd like to stick with this project, that's cool too. I've added some ways you can get around the version limitation in the README, including a blurb on `babel-register` that I added this morning. If you're absolutely stuck in the mud on Node 6, it might be worth having a conversation with the person(s) mandating that policy, as they're holding you back rather significantly.

**Comment by pgn-vole** [comment]
> having a conversation with the person(s) mandating that policy, as they're holding you back rather significantly.

Large organisations  (ours is a 100k+) don't treat IT like a startup would do unfortunately. Changes of runtime version is not taken lightly. And even unthinkable if the version is actually not qualified as LTS.

Anyway we understand your point of view. Thanks for your work on this library it will be very helpful.

**Comment by grancalavera** [comment]
Say no more, thanks for your time @shellscape , we'll find a solution.

**Pull request closed without merging**
